### ISSUE TITLE
Why does List[Int](1, 2, 3).asInput.size return Some(3) instead of Some(12)?

### ISSUE THREAD

**Issue by wspringer** [jesseeichar/scala-io#15]
List[Byte](1, 2, 3).asInput.size returns 3. That makes sense. Every Byte is getting encoded as  a Byte. 

However, I would expect every Int in List[Int](1, 2, 3) to be encoded as four bytes. And hence, I would expect the size to be 12. But it isn't. Why?

**Comment by jesseeichar** [comment]
The wrong converter must be used.  It should be 12.

**Comment by jesseeichar** [comment]
fixed as of 63b7be4d360a347aa512987731a3e02cd8c0b83c (master) 601479e02feeb93d8af3a4a4754cf2fa939f9523 (2.9)
