### ISSUE TITLE
Comparing the contents of two Input objects

### ISSUE THREAD

**Issue by wspringer** [jesseeichar/scala-io#16]
I would love to be able to test if two Input object provide the same sequence of bytes. Currently, I can't do that. Having the ability to do something like this would be awesome:

```
Resource.fromFile(...).hasSameContentsAs(Resource.fromFile(...))
```

In fact, I wonder if we shouldn't be able to define equality in terms of equality of the bytes provided by the objects. AFAICT, this is the way in which the Scala Collection API defines equality of collections.

**Comment by jesseeichar** [comment]
Makes sense.  You have any suggestions on what the API would look like.   Without deep consideration I am thinking something like:

hasSameContentAs(other:Resource[A])(implicit equalStrategy)

but do we need the implicit?

**Comment by wspringer** [comment]
I would expect a method like this to always compare the bytes provided by both resources, and return `true` if they happen to be exactly the same, so I don't think there is a need to have it accept an `equalStrategy`. It's probably best to mimic the collections API as closely as possible. From my point of view, `the hasSameContentsAs` method outlined above would be similar to `sameElements(i: Iterable[..])` on `IterableLike`.

**Comment by jesseeichar** [comment]
+1 from me.  I will implement this.

**Comment by jesseeichar** [comment]
Turned out to be must trickier to implement than I had expected so this required a pretty major refactoring but the benefit is that now it will be easier to compose traversables and impement iteratee pattern.

Done as of commit  7c4204ba16c5353b0d74
