### ISSUE TITLE
Performance issue with bulk copy on small files

### ISSUE THREAD

**Issue by ghost** [jesseeichar/scala-io#43]
I have a small script used to manually replace classfiles produced by Proguard with original ones. It seems to suffer from poor performance during traversals with copying. The script traverses all files under a named directory (here scala-library), finds the relative copy for each item, then stores that copy to a relative destination path. The script assumes scala-library.jar has been extracted to ./copy/scala-library and ./pruned/scala-library.

CopyLibraries.scala:

```
import scalax.file.Path
import scalax.file.PathMatcher._

def copyLibrary(name: String) {
    val copyPath = Path("./copy") / name
    val fromPath = Path("./pruned") / name
    val toPath = Path("./final") / name

    def copyFile(from: Path) {
        val toCopy = copyPath \ from.relativize(fromPath)
        val toMake = toPath \ from.relativize(fromPath)
        toMake.deleteIfExists(force = true)
        toMake.createFile()
        toCopy.copyDataTo(output = toMake, finalize = true)
    }

    fromPath.descendants().collect {
        case item if item.isFile => copyFile(item)
    }
    println("done " + fromPath + " to " + toPath)
}

copyLibrary("scala-library")
```

CopyLibraries.cmd:

```
set LIBS=.\lib\scala-arm_2.9.1-0.3.jar;.\lib\scala-io-core_2.9.1-0.2.0.jar;.\lib\scala-io-file_2.9.1-0.2.0.jar
scala -classpath "%LIBS%" CopyLibraries.scala
```

Setup: scala-io.0.2.0, Scala 2.9.1, java 1.6.27, Windows 7 (32-bit), ssd-disk

**Comment by jesseeichar** [comment]
Thanks for the report Trond.  Performance of various aspects of the library are my current concentration.  At the moment I am really focussing on raw read/write performance and trying to get them down to the equivalent performance an experienced java developer can get from doing the task in Java.

I will create a performance test for this case and try to get some performance improvements for you ASAP

**Comment by jesseeichar** [comment]
I have now doubled the performance but that is not sufficient.  I found that relativize is take nearly 1/4 of the time so I am going to optimize that so that method is quicker.

**Comment by ghost** [comment]
Nice. That will yield quite a noticeable speedup. Hope you manage to nail down more performance problems lurking around.

**Comment by jesseeichar** [comment]
2 more comments:
1.  I am changing how path-sets work so they are lazy like views so you can map and flatmap on large trees and not have memory problems and only hit the drive at the last possible moment.  So doing a side-effecting operation in a collect will have no effect until you call force.
2.  Please continue to make these reports.  I am making lots and lots of performance tests but it is hard to determine the cases I need to optimize for.

**Comment by jesseeichar** [comment]
I have closed this last week really.  I have now copied 3000/directories of 50 bytes each in 500 ms which I think is acceptable.  I am sure I can make it faster but I have bigger issues for now.

**Comment by ghost** [comment]
The 0.3.0 release worked like a charm. Some 30 sec in total when running this script on the scala-library and scala-compiler combined.

**Comment by jesseeichar** [comment]
Thanks for the feedback Trond.  Glad the hard work is paying off.
