### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by JayDaley** [jesseeichar/scala-io#44]
On this page: http://jesseeichar.github.com/scala-io-doc/0.2.0/index.html#!/getting-started

I believe (but I might well be wrong!) that 

`val file = "com.github.scala-incubator.io" %% "scala-io-core" % "0.2.0"`

should say

`val file = "com.github.scala-incubator.io" %% "scala-io-file" % "0.2.0"`

for the SBT `build.sbt` it seems that the needed syntax is

`libraryDependencies += "com.github.scala-incubator.io" %% "scala-io-file" % "0.2.0"`

**Comment by jesseeichar** [comment]
You are correct.  I wrote this when it was still SBT 0.7.  Thanks for noticing that.

**Comment by JayDaley** [comment]
I notice that both lines say `scala-io-core` when one should say `scala-io-file`

**Comment by jesseeichar** [comment]
arg late night fixes.  thanks
