### ISSUE TITLE
NPE when writing to a nonexisting relative path

### ISSUE THREAD

**Issue by jdolson** [jesseeichar/scala-io#45]
```
Path("foobar").write("hello world")
```

throws a `NullPointerException` when "foobar" doesn't exist. the cause is 

```
jfile.getParentFile.mkdirs()    // FileUtils.scala:58
```

because `getParentFile` returns `null`

I'm running scala-io 0.2.0

**Comment by jesseeichar** [comment]
Fixed as of: 5ada794496a537cd502b6a936c183eebd5479152

Thanks for the bug report
