### ISSUE TITLE
src / dst does not work on ubuntu

### ISSUE THREAD

**Issue by arturaz** [jesseeichar/scala-io#53]
https://raw.github.com/gist/1869674/4fda3d47eec03b7993888aa245df77889eb6aad0/gistfile1.txt

Using:

```
    "com.github.scala-incubator.io" %% "scala-io-core" % "0.3.0",
    "com.github.scala-incubator.io" %% "scala-io-file" % "0.3.0"
```

**Comment by jesseeichar** [comment]
This is not a bug.  The children of / must be single segments.  So what you want is either 

```
Path.fromString("/home/arturas/work/spacegame/flex/src-pp") / "config" / "Config.as"
```

or

```
Path.fromString("/home/arturas/work/spacegame/flex/src-pp") / ("config/Config.as", '/') (forth coming in 0.4)
```

or

```
Path.fromString("/home/arturas/work/spacegame/flex/src-pp") resolve ("config/Config.as")
```

**Comment by arturaz** [comment]
Then I'd believe that error message should be clearer.

**Comment by jesseeichar** [comment]
That if a fair point.  I have reopened this issue until I give a good error message.

**Comment by arturaz** [comment]
Cool :) Thanks for quick reply.

**Comment by jesseeichar** [comment]
Updated error message with examples and an explanation of what is potentially the problem:

%s is not permitted as a path 'segment' for this filesystem. Segment in question: %s. " +
         "\nIf you want to create a Path from a system dependent string then use for string. " +
         "If you want to create a child path use resolve instead of / to create the child path. " +
         "It should be noted that the string after '/' must be a single segment but resolve accepts " +
         """full strings. Examples:\n\tPath.fromString("c:\a\b")\n\tpath / ("a/b/c",'/')\n\tpath resolve "a\b\c" """

It is not perfect but gives a better idea of what is happening I think

**Comment by arturaz** [comment]
"use for string" should be "use fromString".

**Comment by arturaz** [comment]
And thanks for your work :)

**Comment by jesseeichar** [comment]
Thank you for the correction.  I have updated it locally and will push soon
