### ISSUE TITLE
'moveTo' poor performance when moving files between different filesystems

### ISSUE THREAD

**Issue by 4e6** [jesseeichar/scala-io#54]
Originally I discovered this issue when tried to move a file from `tmp` (`tmpfs` filesystem, resides in ram) to `home` (`btrfs`) directory and posted on [SO](http://stackoverflow.com/questions/9819100/scala-io-moving-file-from-tmpfs-too-slow).

But after further digging I figured that `moveTo` has bad performance in general when tried to move files between different filesystems. In tests I moved 35MB file between `tmpfs`, `btrfs`, `fat32` and `ext4` and every time average speed was from `500K/s` to `1M/s` according to `iotop`; and process caused 100% cpu load.

Final notes. `moveTo` works fine within the same fs; `copyTo` works fine regardless fs type; `replace` and `atomicMove` flags of `moveTo` method doesn't change anything.

**Comment by jesseeichar** [comment]
I just looked and it is clear that moveTo has an old an inefficient implementation.  I have made a local change and am debugging to ensure that it is as fast as possible.  I will have a fix committed within the hour.

Thanks for the report.

**Comment by jesseeichar** [comment]
Pushed a fix.  I transfered 600 MB between two hardrives, one a USB 2 external drive in 60 seconds.

Fix is commit 7b4b2e7

**Comment by 4e6** [comment]
Wow, what a nice quickfix. Thanks!

**Comment by jesseeichar** [comment]
I have also published to maven snapshots repository: https://oss.sonatype.org/content/repositories/snapshots

But there is a bug with the scala-io-file pom so you need both file and core as dependencies for now.  I am working on a fix for that.
