### ISSUE TITLE
Add ByteStreams.copy(InputStream,OutputStream) equivalent functionality

### ISSUE THREAD

**Issue by jesseeichar** [jesseeichar/scala-io#6]
If you feel this is something that actually should end up on a mailing list somewhere, I'd be happy to do so. (And also tell me where you want me to direct it.)

I am currently running through Scala IO trying to map everything Commons IO and Guava have to offer to something in Scala IO. (Will put it online somewhere soon.) As you noticed this morning, I quickly ran into some roadblocks. Thanks for sorting that out!

Anyway, I am now looking at the ByteStreams.copy(InputStream, OutputStream) operation, and realized that I couldn't find counterpart for it in Scala IO. If I missed on something, then I solemnly swear never to bother you ever again, but perhaps then at least you could tell me where to look for it.

**Comment by jesseeichar** [comment]
Hi,  The ByteStreams.copy functionality is a feature I want to include.  In fact it is one of the features I want to include ASAP as it is required to permit truly performant data transfer.  I am trying to decide how to add it.  

I can't really add a Method copy that takes an input and output stream because one of the principals of the library is to limit how deeply java classes penetrate the API (to make it easier to port to the CLR).  I have already identified a few places where I have made this mistake and need to fix them.  

So some ideas I have are:
- Add to Input a copyTo(Output) method.  The salient question is how to make that efficient.  IE how do you get access to the underlying object in order to perform the copy
- InputResource.copyTo(OutputResource)  This is a bit easier because a resource has access to the underlying object, however it is not intended to be as common of an API as the Input/Output API

I am currently leaning towards Input.copyTo(Output) and override the behavior in InputResource to directly access the inputstream/channel to make the transfer efficient.

**Comment by wspringer** [comment]
I see what you're saying. Implicits come to mind. ;-) 

(In the sense of having the system sort out itself what would be the most appropriate thing to do.)

**Comment by jesseeichar** [comment]
Implicits are an interesting idea.  The draw back to that is for implicits to work you need to somehow expose the type information of the underlying datatype in the signature (or at least a transfer strategy for the underlying data type)  which I would like to avoid.  

Maybe it is possible to have the information optionally used.  I am not completely seeing the design in my head at this point

**Comment by jesseeichar** [comment]
For the first version I have added a copyData(output) method.  I am going to try to optimize it for the next version.
