### ISSUE TITLE
decouple scala-io core from akka

### ISSUE THREAD

**Issue by jedws** [jesseeichar/scala-io#61]
unfortunately, the Akka dependency for AsyncLongTraversable has also added an ExecutionContext to the scala.io package object, this causes compile errors if we try and exclude the akka dependency (as we don't need it and actually don't want it).

At the very least, please move the ExecutionContext instance to the AsyncLongTraversable companion, but ideally move async into its own submodule (a separate module/jar would be ideal)

Obviously this is only for 2.9 due to 2.10 having Future as part of the standard lib.

**Comment by jesseeichar** [comment]
I agree.  I am starting work on two branches one with the future work and one without

**Comment by jedws** [comment]
It isn't that the Future is bad per se, but having the akka reference
in the package object means the classloader tries to load it at the
earliest possible opportunity. Even if you could put the akka
reference in the Async\* companions it would be preferable.

On 6 July 2012 16:04, Jesse Eichar
reply@reply.github.com
wrote:

**Comment by jesseeichar** [comment]
I agree, but to have the future I have to implement the trait then mix in Akka correctly and for the 2.9.x branch it is not high priority for me.  2.10 is the focus now so it can be incorporated into scala core library

**Comment by jesseeichar** [comment]
I have now published 0.4 and 0.4-seq.  Where the -seq version does not have an Akka dependency.

**Comment by jedws** [comment]
excellent, thanks Jesse!

On 30 July 2012 05:34, Jesse Eichar
reply@reply.github.com
wrote:
