### ISSUE TITLE
PathMatcher glob "**/H*"  failed to match the path of exactly one segment

### ISSUE THREAD

**Issue by wks** [jesseeichar/scala-io#62]
As shown on this page:

http://jesseeichar.github.com/scala-io-doc/0.4.1/index.html#!/file/file_system_supported_matchers

The GLOB `**/H*` should match all files whose basename start with H. This is not the case when the Path object contains just the basename.

See: 

``` scala
    val StartsWithH: PathMatcher[Path] = FileSystem.default.matcher("**/H*", GLOB)
    Path("a") / "b" / "c" / "Hit" match {
      case StartsWithH(path) => println("Path name starts with an H")
      case _ => println("Not that case")
    }
    Path("Hit") match {
      case StartsWithH(path) => println("Path name starts with an H")
      case _ => println("Not that case")
    }
```

The previous code matches the first path `a/b/c/Hit`, but not the second path `Hit`. I suppose both paths should be matched.

The glob `H*` will match the second one but not the first one.

So I think _there should be a method to match against only the basename no matter whether the dirname contains zero or more segments_.

**Comment by jesseeichar** [comment]
There are several ways to do this:

```
val StartsWithH: PathMatcher[Path] = FileSystem.default.matcher("(.*/)?H.+", PathMatcher.StandardSyntax.REGEX)
```

or

```
val StartsWithH: PathMatcher[Path] = PathMatcher.GlobNameMatcher("H*")
```

or

```
val StartsWithH: PathMatcher[Path] = PathMatcher.RegexNameMatcher("H.+")
```
