### ISSUE TITLE
scalax.file.NotDirectoryException: null thrown from deleteRecursively

### ISSUE THREAD

**Issue by OlegYch** [jesseeichar/scala-io#78]
For some reason deleteRecursively fails spontaneously  
Apparently scalax.file.Path#children throws NotDirectoryException when it encounters a directory which was already deleted.
This is with 0.4.1

**Comment by jesseeichar** [comment]
I am curious how this this works.  Does it happen when directories are linked together?

**Comment by jesseeichar** [comment]
Or perhaps when 2 processes are running ...

**Comment by jesseeichar** [comment]
Oops sorry about the accidental closure of issue

**Comment by jesseeichar** [comment]
Another comment.  Have you tried settings continueOnFailure to true?

**Comment by OlegYch** [comment]
Forgot to mention, i'm using it like deleteRecursively(force = true, continueOnFailure = true)

Yes, i suspect it happens because another process is also deleting something in that folder.

**Comment by jesseeichar** [comment]
I have done what I can.  I was unable to reproduce it but I put guards around the children calls so in this case the method should continue to run and delete what it can.

I am releasing 0.4.2 with this fix and an upgraded scala-arm as well today.

**Comment by jesseeichar** [comment]
I have deployed but am waiting for all the maven repository caches to be updated.  it is not yet available when searching search.maven.org.  I will update when it is available for general use

**Comment by jesseeichar** [comment]
Finally.  It has appeared in maven central

**Comment by OlegYch** [comment]
Thanks Jesse, works fine.
