### ISSUE TITLE
Publish scala-io for scala 2.11

### ISSUE THREAD

**Issue by mallman** [jesseeichar/scala-io#93]
Please publish a version of scala-io for scala 2.11. Cheers.

**Comment by jesseeichar** [comment]
There is a version for 2.11

http://search.maven.org/#artifactdetails%7Ccom.github.scala-incubator.io%7Cscala-io-file_2.11%7C0.4.3%7Cjar

Jesse

—

**Comment by jesseeichar** [comment]
There is a version for 2.11 

http://search.maven.org/#artifactdetails%7Ccom.github.scala-incubator.io%7Cscala-io-file_2.11%7C0.4.3%7Cjar
